import type { Metadata } from "next";

import "./globals.css";
import {ClerkProvider,} from "@clerk/nextjs";
import {ReactNode} from "react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <ClerkProvider>
          <html lang="en" data-theme="emerald">
          <body>
          {children}
          </body>
          </html>
      </ClerkProvider>
  );
}
